   steps:
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - 'build'
         - '-t'
         - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
         - '-t'
         - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:latest'
         - '.'
       dir: 'materiales/practica-1/ejemplo-app-info-service'
   
     - name: 'gcr.io/cloud-builders/docker'
       args:
         - 'push'
         - '--all-tags'
         - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service'
   
     # Paso 3: Actualizar cloud run para la nueva imagen
     - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
       entrypoint: 'gcloud'
       args:
         - 'run'
         - 'deploy'
         - 'app-info-service'
         - '--image'
         - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
         - '--region'
         - '${_REGION}'
   images:
     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:${BUILD_ID}'
     - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/app-info-service:latest'
   
   substitutions:
     _REGION: 'europe-west1'
     _REPO_NAME: 'docker-repo'
     # Nota: BUILD_ID se usa directamente en los tags (no en substitutions) porque siempre está disponible.
     # Para triggers de Git, puedes cambiar BUILD_ID por SHORT_SHA en los tags si prefieres usar el commit SHA.
   
   options:
     machineType: 'E2_HIGHCPU_8'
     logging: CLOUD_LOGGING_ONLY
   
   timeout: '1200s'
